DROP DATABASE IF EXISTS ETECS;

CREATE DATABASE ETECS;

USE ETECS;

CREATE TABLE ETEC(
ID_ETEC	BIGINT PRIMARY KEY AUTO_INCREMENT,
COD_ETEC int NOT NULL,
NOME_ETEC VARCHAR(60) NOT NULL,
CEP_ETEC VARCHAR(8) NOT NULL,
LAT_CEP DOUBLE NOT NULL,
LONG_CEP DOUBLE NOT NULL,
ENDERECO_ETEC VARCHAR(40) NOT NULL,
BAIRRO_ETEC VARCHAR(40)  NOT NULL,
CIDADE_ETEC VARCHAR(40) NOT NULL,
DATA_INCLUSAO DATETIME NOT NULL
 );